# Run 0, entropy -17.6045, 385 rules
206	Word --> ConsonantsI VowelsF
2793	Word --> ConsonantsI RhymeF
111	Word --> Vowels ConsonantsF
3082	Word --> SyllI Sylls
807	Sylls --> SepSyll Sylls
3082	Sylls --> Separator SyllF
807	SepSyll --> Separator Syll
0	Syll --> Vowel Vowels
5	Syll --> Vowels ConsonantsC
687	Syll --> ConsonantsO Vowels
65	Syll --> ConsonantsO Rhyme
2129	SyllI --> ConsonantsI Vowels
497	SyllI --> ConsonantsI Rhyme
18	SyllI --> Vowel Vowels
125	SyllI --> Vowels ConsonantsC
94	SyllF --> Vowels ConsonantsF
1	SyllF --> Vowel Vowels
1212	SyllF --> ConsonantsO VowelsF
1740	SyllF --> ConsonantsO RhymeF
562	Rhyme --> Vowels ConsonantsC
4533	RhymeF --> Vowels ConsonantsF
87	VowelsF --> VowelF VowelsF
661	Vowels --> Vowel Vowels
1600	ConsonantsI --> ConsonantI ConsonantsI
392	ConsonantsO --> ConsonantO ConsonantsO
8	ConsonantsC --> ConsonantC ConsonantsC
860	ConsonantsF --> ConsonantF ConsonantsF
3889	Separator --> -
0	VowelF --> q
0	VowelF --> U
0	VowelF --> 5
2	VowelF --> E
0	VowelF --> $
16	VowelF --> Q
0	VowelF --> P
0	VowelF --> c
0	VowelF --> u
0	VowelF --> H
0	VowelF --> {
0	VowelF --> i
0	VowelF --> 1
0	VowelF --> 3
0	VowelF --> ~
56	VowelF --> #
0	VowelF --> V
0	VowelF --> @
13	VowelF --> I
0	VowelsF --> q
18	VowelsF --> U
207	VowelsF --> 5
0	VowelsF --> E
25	VowelsF --> $
0	VowelsF --> Q
402	VowelsF --> P
0	VowelsF --> c
94	VowelsF --> u
69	VowelsF --> H
0	VowelsF --> {
56	VowelsF --> i
74	VowelsF --> 1
0	VowelsF --> 3
0	VowelsF --> ~
13	VowelsF --> #
0	VowelsF --> V
257	VowelsF --> @
203	VowelsF --> I
0	Syll --> q
0	Syll --> U
10	Syll --> 5
4	Syll --> E
1	Syll --> $
1	Syll --> Q
0	Syll --> P
0	Syll --> c
0	Syll --> u
0	Syll --> H
1	Syll --> {
1	Syll --> i
3	Syll --> 1
0	Syll --> 3
0	Syll --> ~
4	Syll --> #
0	Syll --> V
24	Syll --> @
1	Syll --> I
24	ConsonantI --> T
0	ConsonantI --> R
0	ConsonantI --> r
1	ConsonantI --> l
0	ConsonantI --> j
0	ConsonantI --> C
1	ConsonantI --> v
0	ConsonantI --> N
7	ConsonantI --> m
0	ConsonantI --> Z
0	ConsonantI --> F
0	ConsonantI --> x
123	ConsonantI --> b
8	ConsonantI --> h
0	ConsonantI --> z
8	ConsonantI --> n
104	ConsonantI --> g
253	ConsonantI --> k
154	ConsonantI --> t
64	ConsonantI --> d
0	ConsonantI --> D
118	ConsonantI --> f
544	ConsonantI --> s
174	ConsonantI --> p
17	ConsonantI --> S
0	ConsonantI --> _
0	ConsonantI --> w
0	ConsonantI --> J
0	ConsonantF --> T
0	ConsonantF --> R
0	ConsonantF --> r
126	ConsonantF --> l
0	ConsonantF --> j
0	ConsonantF --> C
1	ConsonantF --> v
67	ConsonantF --> N
54	ConsonantF --> m
0	ConsonantF --> Z
0	ConsonantF --> F
0	ConsonantF --> x
1	ConsonantF --> b
0	ConsonantF --> h
0	ConsonantF --> z
306	ConsonantF --> n
0	ConsonantF --> g
103	ConsonantF --> k
8	ConsonantF --> t
2	ConsonantF --> d
0	ConsonantF --> D
29	ConsonantF --> f
144	ConsonantF --> s
19	ConsonantF --> p
0	ConsonantF --> S
0	ConsonantF --> _
0	ConsonantF --> w
0	ConsonantF --> J
0	Vowel --> q
32	Vowel --> U
0	Vowel --> 5
48	Vowel --> E
0	Vowel --> $
42	Vowel --> Q
0	Vowel --> P
0	Vowel --> c
0	Vowel --> u
0	Vowel --> H
0	Vowel --> {
0	Vowel --> i
0	Vowel --> 1
0	Vowel --> 3
0	Vowel --> ~
473	Vowel --> #
0	Vowel --> V
0	Vowel --> @
85	Vowel --> I
32	ConsonantsI --> T
0	ConsonantsI --> R
839	ConsonantsI --> r
562	ConsonantsI --> l
147	ConsonantsI --> j
0	ConsonantsI --> C
120	ConsonantsI --> v
0	ConsonantsI --> N
369	ConsonantsI --> m
0	ConsonantsI --> Z
0	ConsonantsI --> F
0	ConsonantsI --> x
308	ConsonantsI --> b
231	ConsonantsI --> h
23	ConsonantsI --> z
163	ConsonantsI --> n
147	ConsonantsI --> g
531	ConsonantsI --> k
351	ConsonantsI --> t
219	ConsonantsI --> d
17	ConsonantsI --> D
207	ConsonantsI --> f
333	ConsonantsI --> s
435	ConsonantsI --> p
95	ConsonantsI --> S
103	ConsonantsI --> _
304	ConsonantsI --> w
89	ConsonantsI --> J
55	ConsonantsF --> T
382	ConsonantsF --> R
0	ConsonantsF --> r
343	ConsonantsF --> l
0	ConsonantsF --> j
0	ConsonantsF --> C
81	ConsonantsF --> v
53	ConsonantsF --> N
252	ConsonantsF --> m
4	ConsonantsF --> Z
0	ConsonantsF --> F
0	ConsonantsF --> x
95	ConsonantsF --> b
0	ConsonantsF --> h
125	ConsonantsF --> z
563	ConsonantsF --> n
95	ConsonantsF --> g
378	ConsonantsF --> k
851	ConsonantsF --> t
370	ConsonantsF --> d
11	ConsonantsF --> D
105	ConsonantsF --> f
428	ConsonantsF --> s
247	ConsonantsF --> p
78	ConsonantsF --> S
99	ConsonantsF --> _
0	ConsonantsF --> w
123	ConsonantsF --> J
0	Vowels --> q
192	Vowels --> U
337	Vowels --> 5
634	Vowels --> E
275	Vowels --> $
574	Vowels --> Q
3	Vowels --> P
0	Vowels --> c
326	Vowels --> u
5	Vowels --> H
915	Vowels --> {
390	Vowels --> i
356	Vowels --> 1
226	Vowels --> 3
0	Vowels --> ~
347	Vowels --> #
508	Vowels --> V
1312	Vowels --> @
1865	Vowels --> I
0	SyllI --> q
0	SyllI --> U
24	SyllI --> 5
21	SyllI --> E
32	SyllI --> $
16	SyllI --> Q
0	SyllI --> P
0	SyllI --> c
2	SyllI --> u
0	SyllI --> H
56	SyllI --> {
12	SyllI --> i
15	SyllI --> 1
4	SyllI --> 3
0	SyllI --> ~
15	SyllI --> #
3	SyllI --> V
83	SyllI --> @
30	SyllI --> I
0	SyllF --> q
0	SyllF --> U
22	SyllF --> 5
0	SyllF --> E
0	SyllF --> $
0	SyllF --> Q
0	SyllF --> P
0	SyllF --> c
0	SyllF --> u
0	SyllF --> H
0	SyllF --> {
1	SyllF --> i
1	SyllF --> 1
0	SyllF --> 3
0	SyllF --> ~
0	SyllF --> #
0	SyllF --> V
10	SyllF --> @
1	SyllF --> I
2	ConsonantO --> T
0	ConsonantO --> R
1	ConsonantO --> r
12	ConsonantO --> l
0	ConsonantO --> j
0	ConsonantO --> C
5	ConsonantO --> v
0	ConsonantO --> N
9	ConsonantO --> m
0	ConsonantO --> Z
0	ConsonantO --> F
0	ConsonantO --> x
28	ConsonantO --> b
1	ConsonantO --> h
0	ConsonantO --> z
20	ConsonantO --> n
25	ConsonantO --> g
58	ConsonantO --> k
62	ConsonantO --> t
19	ConsonantO --> d
0	ConsonantO --> D
16	ConsonantO --> f
109	ConsonantO --> s
25	ConsonantO --> p
0	ConsonantO --> S
0	ConsonantO --> _
0	ConsonantO --> w
0	ConsonantO --> J
0	ConsonantC --> T
0	ConsonantC --> R
0	ConsonantC --> r
0	ConsonantC --> l
0	ConsonantC --> j
0	ConsonantC --> C
0	ConsonantC --> v
1	ConsonantC --> N
4	ConsonantC --> m
0	ConsonantC --> Z
0	ConsonantC --> F
0	ConsonantC --> x
0	ConsonantC --> b
0	ConsonantC --> h
0	ConsonantC --> z
1	ConsonantC --> n
0	ConsonantC --> g
1	ConsonantC --> k
0	ConsonantC --> t
1	ConsonantC --> d
0	ConsonantC --> D
0	ConsonantC --> f
0	ConsonantC --> s
0	ConsonantC --> p
0	ConsonantC --> S
0	ConsonantC --> _
0	ConsonantC --> w
0	ConsonantC --> J
20	ConsonantsO --> T
0	ConsonantsO --> R
467	ConsonantsO --> r
366	ConsonantsO --> l
110	ConsonantsO --> j
0	ConsonantsO --> C
133	ConsonantsO --> v
1	ConsonantsO --> N
238	ConsonantsO --> m
4	ConsonantsO --> Z
0	ConsonantsO --> F
0	ConsonantsO --> x
232	ConsonantsO --> b
17	ConsonantsO --> h
101	ConsonantsO --> z
258	ConsonantsO --> n
165	ConsonantsO --> g
259	ConsonantsO --> k
392	ConsonantsO --> t
251	ConsonantsO --> d
16	ConsonantsO --> D
93	ConsonantsO --> f
235	ConsonantsO --> s
193	ConsonantsO --> p
31	ConsonantsO --> S
66	ConsonantsO --> _
32	ConsonantsO --> w
24	ConsonantsO --> J
2	ConsonantsC --> T
0	ConsonantsC --> R
0	ConsonantsC --> r
63	ConsonantsC --> l
0	ConsonantsC --> j
0	ConsonantsC --> C
1	ConsonantsC --> v
79	ConsonantsC --> N
143	ConsonantsC --> m
0	ConsonantsC --> Z
0	ConsonantsC --> F
0	ConsonantsC --> x
5	ConsonantsC --> b
0	ConsonantsC --> h
14	ConsonantsC --> z
229	ConsonantsC --> n
17	ConsonantsC --> g
60	ConsonantsC --> k
15	ConsonantsC --> t
9	ConsonantsC --> d
0	ConsonantsC --> D
6	ConsonantsC --> f
30	ConsonantsC --> s
17	ConsonantsC --> p
2	ConsonantsC --> S
0	ConsonantsC --> _
0	ConsonantsC --> w
0	ConsonantsC --> J

