(TeX-add-style-hook "lex"
 (lambda ()
    (LaTeX-add-bibliographies
     "/Users/km/Dropbox/lyx/refs")
    (LaTeX-add-labels
     "probvfreq"
     "neighborsvfreq"
     "cor.test"
     "cor.table"
     "fig:pairs"
     "3pairs"
     "3onset"
     "levs"
     "fig:toy"
     "fig:networks"
     "3net")
    (TeX-run-style-hooks
     "placeins"
     "hyperref"
     "float"
     "datatool"
     "fontenc"
     "T1"
     "csvtools"
     "tipa"
     "amssymb"
     "amsthm"
     "amsmath"
     "tocbibind"
     "nottoc"
     "fancyhdr"
     "caption"
     "qtree"
     "apacite"
     "pslatex"
     "authblk"
     "latex2e"
     "art10"
     "article")))

